# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# 새로 추가한 부분 
env: 
  S3_BUCKET_NAME: build-file-storage 
  PROJECT_NAME: jdbc_template_test
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8 
        uses: actions/setup-java@v1 
        with: 
          java-version: 1.8 
      
      - name: Grant execute permission for gradlew 
        run: chmod +x gradlew 
        shell: bash 
      
      - name: Build with Gradle 
        run: ./gradlew build --exclude-task test                                                       
        shell: bash
        
     ### S3에 빌드파일 업로드 부분 ### 
      - name: Make zip file 
        run: zip -r ./$GITHUB_SHA.zip . 
        shell: bash 

      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1 
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: ${{ secrets.AWS_REGION }} 

      - name: Upload to S3 
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip
        
      ### S3의 빌드파일로 배포 실행 ### 
      - name: Code Deploy 
        run: aws deploy create-deployment --application-name deploy-server --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name was --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
